---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-static-data-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi


